{
 "title": "SMProxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sp_swoole_version, instance)"
    }
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(sp_db_max_connection,db)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Swoole worker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sp_swoole_worker_num{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "All Connection usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sp_connection_info_time{instance=\"$instance\",command=~\"Query\"})/sum(sp_db_max_connection{instance=\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "$db  - Connection usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sp_connection_info_time{instance=\"$instance\",db=\"$db\",command=~\"Query\"})/sum(sp_db_max_connection{instance=\"$instance\",db=\"$db\"}) * 100"
    }
   ]
  },
  {
   "title": "Connection Count Status Pie Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sp_connection_info_time{instance=\"$instance\",db=\"$db\",command=~\"Query\"})",
     "legendFormat": "Busy connection"
    },
    {
     "expr": "count(sp_connection_info_time{instance=\"$instance\",db=\"$db\",command!~\"Query\"})",
     "legendFormat": "Idle connection"
    }
   ]
  },
  {
   "title": "SMProxy MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sp_db_max_connection{instance=\"$instance\",db=\"$db\"}",
     "legendFormat": "Max connections"
    },
    {
     "expr": "count(sp_connection_info_time{instance=\"$instance\",db=\"$db\",command=~\"Query\"})",
     "legendFormat": "Connection"
    }
   ]
  },
  {
   "title": "Connection idle time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sp_connection_info_time{instance=\"$instance\",db=\"$db\"}",
     "legendFormat": "Connect ID:{{id}}"
    }
   ]
  }
 ]
}